kinematics:
  joint_a1:
    x: 0
    y: 0
    z: 0.675
    roll: 0
    pitch: 0
    yaw: 0
  joint_a2:
    x: 0.35
    y: 0
    z: 0
    roll: 0
    pitch: 0
    yaw: 0
  joint_a3:
    x: 1.150
    y: 0
    z: 0
    roll: 0
    pitch: 0
    yaw: 0
  joint_a4:
    x: 1.0
    y: 0
    z: -0.041
    roll: 0
    pitch: 0
    yaw: 0
  joint_a5:
    x: 0
    y: 0
    z: 0
    roll: 0
    pitch: 0
    yaw: 0
  joint_a6:
    x: 0
    y: 0
    z: 0
    roll: 0
    pitch: 0
    yaw: 0
  joint_a6-tool0:
    x: 0.240
    y: 0
    z: 0
    roll: 0
    pitch: 1.5707963267948966
    yaw: 0 